import "./globals.css";
import { Cta, Header } from "@/components";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <ToastContainer />
        {children}
        <Cta />
      </body>
    </html>
  );
}
